# Generated by Django 4.2.16 on 2025-06-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('viewed', 'Просмотрено')], default='pending', max_length=20),
        ),
    ]
