# Generated by Django 4.2.16 on 2025-06-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_notifications', to='api.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('invite', 'Приглашение'), ('exclude', 'Исключение из группы'), ('reminder', 'Напоминание о дедлайне')], max_length=20),
        ),
    ]
